# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Htlaeh' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Htlaeh
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Fabric'
  pod 'Digits'
  pod 'TwitterCore'
  pod 'RealmSwift'
  
  target 'HtlaehTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HtlaehUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
